name: comp_ling_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- pandas=2.2.3
- numpy=2.2.3
- pip
- transformers=4.49.0
- pip:
  - regex
  - pygrep
  - flashtext
  - spacy
  - loguru
  - pyspark=3.5.4
  - kafka-python
  - warcio
  - kagglehub