name: comp_ling_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- pandas
- numpy
- pip
- transformers
- PIL
- pip:
  - regex
  - pygrep
  - flashtext
  - spacy
  - loguru
  - pyspark
  - kafka-python
  - warcio
  - kagglehub